import "./globals.css";
import Header from "@/components/Navigation";
import Footer from "@/components/Footer";
import { ReduxProvider } from "@/redux/provider";
import ModalComponent from "../components/Modal";

export const metadat = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <ReduxProvider>
          <div>
            <Header />
            {children}
            <Footer />
          </div>
          <ModalComponent />
        </ReduxProvider>
      </body>
    </html>
  );
}
